services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: spring-modulith
    ports:
      - '5433:5432'
    volumes:
      - spring-modulith-data:/var/lib/postgresql/data
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'

volumes:
  spring-modulith-data: